export const products = [
  // {
  //   PN: "31.5-inch module",
  //   "Display Mode": "VA / Reflective",
  //   "Display Size": "31.5”",
  //   "Dot Format": "1920 x RGB x 1080",
  //   "Color Depth": "16.77M",
  //   "I/F": "eDP/LVDS",
  //   "Operating Temperature": "-20C to +70C",
  //   "60Hz Power": "< 2W",
  //   DOCUMENTS: [],
  //   desc:
  //     "This 31.5-inch (diagonal) reflective display brings all the power of Sharp IGZO to your designs. It’s perfect for outdoor viewability in products such as battery-powered signage, and other high ambient light applications that require low power operation. The display offers ultra-low power consumption for both still and motion images, and a low-power refresh rate without flicker. It features full color with a 28% NTSC ratio, and its wide viewing angles combine with high contrast for vivid images. It also delivers industrial strength operating temperature ranges. Now available in eDP; an LVDS interface version is coming soon. ",
  // },
  {
    PN: "5-inch module",
    "Backlight Brightness": "150nits @ 855mW",
    "Display Mode": "VA / Reflective",
    "Display Size": "5.0 inch",
    "Dot Format": "720 x RGB x 1280",
    "Color Depth": "16.77M",
    "I/F": "MIPI",
    "Operating Temperature": "-20C to +70C",
    img: require("../assets/Sharp-5-inch-R-IGZO.png"),
    "60Hz Panel Power": "< 150mW",
    DOCUMENTS: [],
    desc:
      "This 5.0-inch (diagonal) Reflective IGZO portrait-mode display is ideal for battery-powered, handheld products that require full-color and high-resolution performance in bright outdoor environments. The panel, built on Sharp’s industry-leading IGZO technology, offers ultra-low power consumption for both still and motion images, and allows for slim product profiles with reduced thermal management requirements. The MIPI interface display also delivers industrial strength operating temperature ranges. ",
  },
  {
    "Display Size": "31.5 inch",
    img: require("../assets/Sharp-31.5-inch R-IGZO-LS315M7JX01.png"),
    desc:
      "This 31.5-inch (diagonal) reflective display brings all the power of Sharp IGZO to your designs. It’s perfect for outdoor viewability in products such as battery-powered signage, and other high ambient light applications that require low power operation. The display offers ultra-low power consumption for both still and motion images, and a low-power refresh rate without flicker. It features full color with a 28% NTSC ratio, and its wide viewing angles combine with high contrast for vivid images. It also delivers industrial strength operating temperature ranges.",
    PN: "31.5-inch module",
    "Backlight Brightness": "27nits @ 3.5W",
    "LIFE CYCLE": "Production",
    "CONTRAST RATIO": "17:1 (Reflective Mode)",
    REFLECTANCE: "9%",
    "Color Depth": "16.77M",
    "I/F": "eDP",
    "Dot Format": "1920 x RGB x 1080",
    "Operating Temperature": "-20C to +70C",
    "60Hz Panel Power": "< 2W",
    "Display Mode": "VA/ Reflective",
    "NUMBER OF COLORS": "16.7M",
    "STORAGE TEMP": "-20°C to +70°C",
    "OUTLINE DIMENSIONS": "734 x 420 x 17.70 mm",
    "PIXEL FORMAT": "1920 x 1080",
    "RESPONSE TIME": "20 ms",
    "View Angles (U/D/L/R)": "80°/80°/80°/80°",
    DOCUMENTS: [
      {
        name: "Sharp-Specification-LS315M7JX01",
        link: require("../assets/Documents/Sharp-Specification-LS315M7JX01.pdf"),
      },
    ],
    Applications:
      "Outdoor Signage, Portable Signage, Remote Signage (Solar Powered), POE Signage (Power Over Ethernet)",
  },
];
